require('dotenv').config()

const PORT = process.env.PORT || 3001
let DATABASE_FILE = process.env.DATABASE_FILE

if (process.env.NODE_ENV === 'testing') {
  DATABASE_FILE = process.env.TESTING_DATABASE_FILE
}

const DEFAULT_GET_TVIIT_LIMIT = process.env.DEFAULT_GET_TVIIT_LIMIT

const MIN_SEARCH_LENGTH = process.env.MIN_SEARCH_LENGTH

const MIN_TVIIT_CONTENT_LENGTH = process.env.MIN_TVIIT_CONTENT_LENGTH
const MAX_TVIIT_CONTENT_LENGTH = process.env.MAX_TVIIT_CONTENT_LENGTH

const MIN_PASSWORD_LENGTH = process.env.MIN_PASSWORD_LENGTH
const MAX_PASSWORD_LENGTH = process.env.MAX_PASSWORD_LENGTH

const MIN_USERNAME_LENGTH = process.env.MIN_USERNAME_LENGTH
const MAX_USERNAME_LENGTH = process.env.MAX_USERNAME_LENGTH

const MIN_BIO_LENGTH = process.env.MIN_BIO_LENGTH
const MAX_BIO_LENGTH = process.env.MAX_BIO_LENGTH

const MIN_NAME_LENGTH = process.env.MIN_NAME_LENGTH
const MAX_NAME_LENGTH = process.env.MAX_NAME_LENGTH

const JWT_SECRET = process.env.JWT_SECRET

module.exports = {
  PORT,
  DATABASE_FILE,
  DEFAULT_GET_TVIIT_LIMIT,
  MIN_SEARCH_LENGTH,
  MIN_TVIIT_CONTENT_LENGTH,
  MAX_TVIIT_CONTENT_LENGTH,
  MIN_PASSWORD_LENGTH,
  MAX_PASSWORD_LENGTH,
  MIN_USERNAME_LENGTH,
  MAX_USERNAME_LENGTH,
  MIN_BIO_LENGTH,
  MAX_BIO_LENGTH,
  MIN_NAME_LENGTH,
  MAX_NAME_LENGTH,
  JWT_SECRET
}